#
# Dockerfile for format service
#

FROM java:openjdk-8-jre
MAINTAINER Ray Poling <ruguerv@gmail.com>
ENV REFRESHED_AT 2014-11-25

COPY target/format-0.1.0-SNAPSHOT-standalone.jar format-0.1.0-SNAPSHOT-standalone.jar

ENV PLAYLIST_HOST $PLAYLIST_HOST
ENV PLAYLIST_PORT $PLAYLIST_PORT
ENV SCHEDULE_HOST $SCHEDULE_HOST
ENV SCHEDULE_PORT $SCHEDULE_PORT
ENV USER_HOST     $USER_HOST
ENV USER_PORT     $USER_PORT
ENV LOCATOR_HOST  $LOCATOR_HOST
ENV LOCATOR_PORT  $LOCATOR_PORT
ENV META_HOST     $META_HOST
ENV META_PORT     $META_PORT

ENV PORT 4009

EXPOSE 4009

CMD ["java", "-jar", "format-0.1.0-SNAPSHOT-standalone.jar"]
