CREATE CONSTRAINT ON (node:SERIES) ASSERT node.catalog_id IS UNIQUE;
CREATE CONSTRAINT ON (node:SEASON) ASSERT node.catalog_id IS UNIQUE;
CREATE CONSTRAINT ON (node:EPISODE) ASSERT node.catalog_id IS UNIQUE;
CREATE CONSTRAINT ON (node:TAG) ASSERT node.tag IS UNIQUE;
